Repository razor-network/oracle-node, pull requests merged in 2022-07, with the labels that each got.

#799 Hotfix-bounty Id from events
  cmd/dispute.go
  cmd/dispute_test.go
  utils/block_test.go
Labels: v1

#802 Removed auto unstake and withdraw from vote
  cmd/interface.go
  cmd/mocks/utils_cmd_interface.go
  cmd/vote.go
  cmd/vote_test.go
Labels: v1

#804 Remove features from razor-go
  README.md
  accounts/mocks/account_interface.go
  cmd/addStake.go
  cmd/addStake_test.go
  cmd/claimBounty.go
  cmd/claimBounty_test.go
  cmd/claimCommission.go
  cmd/claimCommission_test.go
  cmd/create.go
  cmd/createCollection.go
  cmd/createCollection_test.go
  cmd/createJob.go
  cmd/createJob_test.go
  cmd/create_test.go
  cmd/delegate.go
  cmd/delegate_test.go
  cmd/initiateWithdraw.go
  cmd/initiateWithdraw_test.go
  cmd/interface.go
  cmd/mocks/flag_set_interface.go
  cmd/mocks/utils_cmd_interface.go
  cmd/mocks/utils_interface.go
  cmd/modifyCollectionStatus.go
  cmd/modifyCollectionStatus_test.go
  cmd/resetUnstakeLock.go
  cmd/resetUnstakeLock_test.go
  cmd/setDelegation.go
  cmd/setDelegation_test.go
  cmd/struct-utils.go
  cmd/transfer.go
  cmd/transfer_test.go
  cmd/unlockWithdraw.go
  cmd/unlockWithdraw_test.go
  cmd/unstake.go
  cmd/unstake_test.go
  cmd/updateCollection.go
  cmd/updateCollection_test.go
  cmd/updateCommission.go
  cmd/updateCommission_test.go
  cmd/updateJob.go
  cmd/updateJob_test.go
  cmd/vote.go
  cmd/vote_test.go
  path/mocks/os_interface.go
  path/mocks/path_interface.go
  utils/password.go
Labels: v1

#819 Rogue mode on biggestStakerId
  cmd/dispute.go
  cmd/interface.go
  cmd/mocks/utils_cmd_interface.go
  cmd/propose.go
  cmd/propose_test.go
Labels: v1

#828 Updated setDelegation command's help
  cmd/setDelegation.go
Labels: v1

#827 Fix : IF condition should be placed before calculating transaction options
  cmd/dispute.go
Labels: v1

#880 Moved path.go strings to constants.go
  core/constants.go
  path/path.go
  path/path_test.go
Labels: code cleanup

#879 Code cleanup
  cmd/claimBounty.go
  cmd/claimCommission.go
  cmd/claimCommission_test.go
  cmd/cmd-utils.go
  cmd/cmd-utils_test.go
  cmd/commit.go
  cmd/commit_test.go
  cmd/dispute.go
  cmd/dispute_test.go
  cmd/initiateWithdraw.go
  cmd/interface.go
  cmd/mocks/stake_manager_interface.go
  cmd/mocks/utils_cmd_interface.go
  cmd/mocks/utils_interface.go
  cmd/propose.go
  cmd/propose_test.go
  cmd/reveal.go
  cmd/reveal_test.go
  cmd/struct-utils.go
  cmd/updateCommission.go
  cmd/vote.go
  cmd/vote_test.go
  core/constants.go
  utils/common.go
  utils/common_test.go
  utils/interface.go
  utils/mocks/utils.go
Labels: code cleanup

#895 Add ETA to unlockWithdraw
  cmd/initiateWithdraw.go
  cmd/unlockWithdraw.go
  cmd/unlockWithdraw_test.go
Labels: enhancement
